name: Build Jarvis APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build Jarvis APK
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Jarvis
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools platforms;android-35 build-tools;35.0.0'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Find APK
        run: |
          echo "APK files:"
          find . -type f -name "*.apk" -print

      - name: Upload Jarvis APK
        uses: actions/upload-artifact@v4
        with:
          name: Jarvis-APK
          path: |
            **/build/outputs/apk/debug/*.apk
          if-no-files-found: error
